# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'blue.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(818, 600)
        MainWindow.setMinimumSize(QtCore.QSize(818, 600))
        MainWindow.setMaximumSize(QtCore.QSize(818, 600))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 47, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 47, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 146, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 47, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 47, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 49, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 49, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 146, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 49, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 49, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.centralwidget.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("MF YueHei (Noncommercial)")
        self.centralwidget.setFont(font)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_center = QtWidgets.QWidget(self.centralwidget)
        self.widget_center.setGeometry(QtCore.QRect(9, 0, 800, 600))
        font = QtGui.QFont()
        font.setFamily("MF YueHei (Noncommercial)")
        self.widget_center.setFont(font)
        self.widget_center.setObjectName("widget_center")
        self.label = QtWidgets.QLabel(self.widget_center)
        self.label.setGeometry(QtCore.QRect(0, 0, 18, 600))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 190, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 190, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 190, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 190, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label.setPalette(palette)
        self.label.setAutoFillBackground(True)
        self.label.setText("")
        self.label.setObjectName("label")
        self.widget1 = QtWidgets.QWidget(self.widget_center)
        self.widget1.setGeometry(QtCore.QRect(177, 29, 623, 571))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget1.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(11)
        self.widget1.setFont(font)
        self.widget1.setAutoFillBackground(True)
        self.widget1.setObjectName("widget1")
        self.lb_tree = QtWidgets.QLabel(self.widget1)
        self.lb_tree.setGeometry(QtCore.QRect(22, 269, 214, 259))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(112, 112, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 149, 149))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(112, 112, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 149, 149))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(112, 112, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(112, 112, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 149, 149))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(112, 112, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(112, 112, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.lb_tree.setPalette(palette)
        self.lb_tree.setAutoFillBackground(False)
        self.lb_tree.setText("")
        self.lb_tree.setScaledContents(True)
        self.lb_tree.setObjectName("lb_tree")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 623, 9))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 190, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 190, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 190, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 190, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_2.setPalette(palette)
        self.label_2.setAutoFillBackground(True)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget1)
        self.label_3.setGeometry(QtCore.QRect(55, 37, 119, 121))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("res/时间_05.png"))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget1)
        self.label_4.setGeometry(QtCore.QRect(250, 37, 122, 115))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("res/目标_07.png"))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget1)
        self.label_5.setGeometry(QtCore.QRect(428, 37, 150, 128))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("res/成就_03.png"))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget1)
        self.label_6.setGeometry(QtCore.QRect(24, 197, 30, 30))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("res/star.png"))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.lb_days = QtWidgets.QLabel(self.widget1)
        self.lb_days.setGeometry(QtCore.QRect(50, 160, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(11)
        self.lb_days.setFont(font)
        self.lb_days.setStyleSheet("color: #ec6a00")
        self.lb_days.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_days.setWordWrap(False)
        self.lb_days.setObjectName("lb_days")
        self.lb_tian_2 = QtWidgets.QLabel(self.widget1)
        self.lb_tian_2.setGeometry(QtCore.QRect(311, 160, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(11)
        self.lb_tian_2.setFont(font)
        self.lb_tian_2.setStyleSheet("color: #1b1f20")
        self.lb_tian_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_tian_2.setWordWrap(False)
        self.lb_tian_2.setObjectName("lb_tian_2")
        self.lb_goal = QtWidgets.QLabel(self.widget1)
        self.lb_goal.setGeometry(QtCore.QRect(250, 160, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(11)
        self.lb_goal.setFont(font)
        self.lb_goal.setStyleSheet("color: #ec6a00")
        self.lb_goal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_goal.setWordWrap(False)
        self.lb_goal.setObjectName("lb_goal")
        self.lb_tian_3 = QtWidgets.QLabel(self.widget1)
        self.lb_tian_3.setGeometry(QtCore.QRect(510, 160, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(11)
        self.lb_tian_3.setFont(font)
        self.lb_tian_3.setStyleSheet("color: #1b1f20")
        self.lb_tian_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_tian_3.setWordWrap(False)
        self.lb_tian_3.setObjectName("lb_tian_3")
        self.lb_achv = QtWidgets.QLabel(self.widget1)
        self.lb_achv.setGeometry(QtCore.QRect(420, 160, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(11)
        self.lb_achv.setFont(font)
        self.lb_achv.setStyleSheet("color: #ec6a00")
        self.lb_achv.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_achv.setWordWrap(False)
        self.lb_achv.setObjectName("lb_achv")
        self.lb_welcom = QtWidgets.QLabel(self.widget1)
        self.lb_welcom.setGeometry(QtCore.QRect(74, 197, 111, 38))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.lb_welcom.setFont(font)
        self.lb_welcom.setAutoFillBackground(False)
        self.lb_welcom.setStyleSheet("color: #757575")
        self.lb_welcom.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_welcom.setObjectName("lb_welcom")
        self.lb_welcom_2 = QtWidgets.QLabel(self.widget1)
        self.lb_welcom_2.setGeometry(QtCore.QRect(22, 229, 581, 38))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lb_welcom_2.setFont(font)
        self.lb_welcom_2.setAutoFillBackground(False)
        self.lb_welcom_2.setStyleSheet("color: #757575")
        self.lb_welcom_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_welcom_2.setObjectName("lb_welcom_2")
        self.widget = QtWidgets.QWidget(self.widget1)
        self.widget.setGeometry(QtCore.QRect(257, 269, 343, 259))
        self.widget.setObjectName("widget")
        self.verticalWidget = QtWidgets.QWidget(self.widget)
        self.verticalWidget.setGeometry(QtCore.QRect(0, 0, 51, 224))
        self.verticalWidget.setStyleSheet("color: #1b1f20")
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_18 = QtWidgets.QLabel(self.verticalWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: #1b1f20")
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout.addWidget(self.label_18)
        self.label_17 = QtWidgets.QLabel(self.verticalWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: #1b1f20")
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout.addWidget(self.label_17)
        self.label_19 = QtWidgets.QLabel(self.verticalWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: #1b1f20")
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout.addWidget(self.label_19)
        self.label_21 = QtWidgets.QLabel(self.verticalWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: #1b1f20")
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout.addWidget(self.label_21)
        self.label_20 = QtWidgets.QLabel(self.verticalWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: #1b1f20")
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout.addWidget(self.label_20)
        self.label_22 = QtWidgets.QLabel(self.verticalWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: #1b1f20")
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout.addWidget(self.label_22)
        self.label_10 = QtWidgets.QLabel(self.verticalWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: #1b1f20")
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.horizontalWidget = QtWidgets.QWidget(self.widget)
        self.horizontalWidget.setGeometry(QtCore.QRect(51, 220, 291, 41))
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_24 = QtWidgets.QLabel(self.horizontalWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: #1b1f20")
        self.label_24.setScaledContents(False)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout.addWidget(self.label_24)
        self.label_26 = QtWidgets.QLabel(self.horizontalWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: #1b1f20")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout.addWidget(self.label_26)
        self.label_25 = QtWidgets.QLabel(self.horizontalWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: #1b1f20")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout.addWidget(self.label_25)
        self.label_23 = QtWidgets.QLabel(self.horizontalWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: #1b1f20")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout.addWidget(self.label_23)
        self.gridLayoutWidget = QtWidgets.QWidget(self.widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 0, 281, 221))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lb_welcomname = QtWidgets.QLabel(self.widget1)
        self.lb_welcomname.setGeometry(QtCore.QRect(180, 197, 401, 38))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lb_welcomname.setFont(font)
        self.lb_welcomname.setAutoFillBackground(False)
        self.lb_welcomname.setStyleSheet("color: #757575")
        self.lb_welcomname.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_welcomname.setObjectName("lb_welcomname")
        self.lb_tian_4 = QtWidgets.QLabel(self.widget1)
        self.lb_tian_4.setGeometry(QtCore.QRect(130, 160, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(11)
        self.lb_tian_4.setFont(font)
        self.lb_tian_4.setStyleSheet("color: #1b1f20")
        self.lb_tian_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_tian_4.setWordWrap(False)
        self.lb_tian_4.setObjectName("lb_tian_4")
        self.lb1 = QtWidgets.QLabel(self.widget_center)
        self.lb1.setGeometry(QtCore.QRect(18, 216, 159, 33))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.lb1.setFont(font)
        self.lb1.setAutoFillBackground(True)
        self.lb1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb1.setObjectName("lb1")
        self.lb4 = QtWidgets.QLabel(self.widget_center)
        self.lb4.setGeometry(QtCore.QRect(18, 315, 159, 33))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.lb4.setFont(font)
        self.lb4.setAutoFillBackground(True)
        self.lb4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb4.setObjectName("lb4")
        self.lb3 = QtWidgets.QLabel(self.widget_center)
        self.lb3.setGeometry(QtCore.QRect(18, 282, 159, 33))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.lb3.setFont(font)
        self.lb3.setAutoFillBackground(True)
        self.lb3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb3.setObjectName("lb3")
        self.lb2 = QtWidgets.QLabel(self.widget_center)
        self.lb2.setGeometry(QtCore.QRect(18, 249, 159, 33))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.lb2.setFont(font)
        self.lb2.setAutoFillBackground(True)
        self.lb2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb2.setObjectName("lb2")
        self.lb_avata = QtWidgets.QLabel(self.widget_center)
        self.lb_avata.setGeometry(QtCore.QRect(41, 36, 115, 115))
        self.lb_avata.setStyleSheet("")
        self.lb_avata.setText("")
        self.lb_avata.setScaledContents(True)
        self.lb_avata.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_avata.setObjectName("lb_avata")
        self.lb_exit = QtWidgets.QLabel(self.widget_center)
        self.lb_exit.setGeometry(QtCore.QRect(41, 520, 120, 38))
        self.lb_exit.setText("")
        self.lb_exit.setPixmap(QtGui.QPixmap("res/fis1h_03.png"))
        self.lb_exit.setScaledContents(True)
        self.lb_exit.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_exit.setObjectName("lb_exit")
        self.lb_nick = QtWidgets.QLabel(self.widget_center)
        self.lb_nick.setGeometry(QtCore.QRect(18, 160, 159, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.lb_nick.setFont(font)
        self.lb_nick.setStyleSheet("color: #e0e0e0")
        self.lb_nick.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_nick.setWordWrap(True)
        self.lb_nick.setObjectName("lb_nick")
        self.lb_lv = QtWidgets.QLabel(self.widget_center)
        self.lb_lv.setGeometry(QtCore.QRect(18, 184, 159, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.lb_lv.setFont(font)
        self.lb_lv.setStyleSheet("color: #e0e0e0")
        self.lb_lv.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_lv.setWordWrap(True)
        self.lb_lv.setObjectName("lb_lv")
        self.label_8 = QtWidgets.QLabel(self.widget_center)
        self.label_8.setGeometry(QtCore.QRect(120, 580, 63, 15))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:  #757575")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.lb5 = QtWidgets.QLabel(self.widget_center)
        self.lb5.setGeometry(QtCore.QRect(18, 348, 159, 33))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.lb5.setFont(font)
        self.lb5.setAutoFillBackground(True)
        self.lb5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb5.setObjectName("lb5")
        self.widget2 = QtWidgets.QWidget(self.widget_center)
        self.widget2.setGeometry(QtCore.QRect(177, 29, 623, 571))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget2.setPalette(palette)
        self.widget2.setAutoFillBackground(True)
        self.widget2.setObjectName("widget2")
        self.label_9 = QtWidgets.QLabel(self.widget2)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 623, 9))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 190, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 190, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 190, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 190, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_9.setPalette(palette)
        self.label_9.setAutoFillBackground(True)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.lb_back2 = QtWidgets.QLabel(self.widget2)
        self.lb_back2.setGeometry(QtCore.QRect(33, 33, 28, 30))
        self.lb_back2.setText("")
        self.lb_back2.setPixmap(QtGui.QPixmap("res/return.png"))
        self.lb_back2.setScaledContents(True)
        self.lb_back2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_back2.setObjectName("lb_back2")
        self.lb_tree_big = QtWidgets.QLabel(self.widget2)
        self.lb_tree_big.setGeometry(QtCore.QRect(129, 123, 294, 367))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(112, 112, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 149, 149))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(112, 112, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 149, 149))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(112, 112, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(112, 112, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 149, 149))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(112, 112, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(112, 112, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.lb_tree_big.setPalette(palette)
        self.lb_tree_big.setAutoFillBackground(False)
        self.lb_tree_big.setText("")
        self.lb_tree_big.setScaledContents(True)
        self.lb_tree_big.setObjectName("lb_tree_big")
        self.lb_jiaoshui = QtWidgets.QLabel(self.widget2)
        self.lb_jiaoshui.setGeometry(QtCore.QRect(454, 63, 118, 118))
        self.lb_jiaoshui.setText("")
        self.lb_jiaoshui.setPixmap(QtGui.QPixmap("res/water.png"))
        self.lb_jiaoshui.setScaledContents(True)
        self.lb_jiaoshui.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_jiaoshui.setObjectName("lb_jiaoshui")
        self.lb_shifei = QtWidgets.QLabel(self.widget2)
        self.lb_shifei.setGeometry(QtCore.QRect(454, 218, 118, 118))
        self.lb_shifei.setText("")
        self.lb_shifei.setPixmap(QtGui.QPixmap("res/shifei.png"))
        self.lb_shifei.setScaledContents(True)
        self.lb_shifei.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_shifei.setObjectName("lb_shifei")
        self.lb_welcom_4 = QtWidgets.QLabel(self.widget2)
        self.lb_welcom_4.setGeometry(QtCore.QRect(170, 500, 91, 38))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lb_welcom_4.setFont(font)
        self.lb_welcom_4.setAutoFillBackground(False)
        self.lb_welcom_4.setStyleSheet("color: #757575")
        self.lb_welcom_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_welcom_4.setObjectName("lb_welcom_4")
        self.lb_growth = QtWidgets.QLabel(self.widget2)
        self.lb_growth.setGeometry(QtCore.QRect(270, 500, 101, 38))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lb_growth.setFont(font)
        self.lb_growth.setAutoFillBackground(False)
        self.lb_growth.setStyleSheet("color: rgb(254, 190, 0)")
        self.lb_growth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_growth.setObjectName("lb_growth")
        self.lb_welcom_6 = QtWidgets.QLabel(self.widget2)
        self.lb_welcom_6.setGeometry(QtCore.QRect(370, 500, 41, 38))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lb_welcom_6.setFont(font)
        self.lb_welcom_6.setAutoFillBackground(False)
        self.lb_welcom_6.setStyleSheet("color: #757575")
        self.lb_welcom_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_welcom_6.setObjectName("lb_welcom_6")
        self.widget3 = QtWidgets.QWidget(self.widget_center)
        self.widget3.setGeometry(QtCore.QRect(177, 29, 623, 571))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget3.setPalette(palette)
        self.widget3.setAutoFillBackground(True)
        self.widget3.setObjectName("widget3")
        self.label_11 = QtWidgets.QLabel(self.widget3)
        self.label_11.setGeometry(QtCore.QRect(0, 0, 623, 9))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 190, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 190, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 190, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 190, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_11.setPalette(palette)
        self.label_11.setAutoFillBackground(True)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.lb_back3 = QtWidgets.QLabel(self.widget3)
        self.lb_back3.setGeometry(QtCore.QRect(33, 33, 28, 30))
        self.lb_back3.setText("")
        self.lb_back3.setPixmap(QtGui.QPixmap("res/return.png"))
        self.lb_back3.setScaledContents(True)
        self.lb_back3.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_back3.setObjectName("lb_back3")
        self.label_12 = QtWidgets.QLabel(self.widget3)
        self.label_12.setGeometry(QtCore.QRect(56, 73, 109, 109))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("res/戒撸时间_07.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_27 = QtWidgets.QLabel(self.widget3)
        self.label_27.setGeometry(QtCore.QRect(43, 239, 150, 113))
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap("res/检测目标_11.png"))
        self.label_27.setScaledContents(True)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.widget3)
        self.label_28.setGeometry(QtCore.QRect(58, 417, 143, 80))
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap("res/游戏设定_15.png"))
        self.label_28.setScaledContents(True)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.lb_save = QtWidgets.QLabel(self.widget3)
        self.lb_save.setGeometry(QtCore.QRect(549, 24, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(13)
        self.lb_save.setFont(font)
        self.lb_save.setPixmap(QtGui.QPixmap("res/save_03.png"))
        self.lb_save.setScaledContents(False)
        self.lb_save.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_save.setObjectName("lb_save")
        self.lb_save_2 = QtWidgets.QLabel(self.widget3)
        self.lb_save_2.setGeometry(QtCore.QRect(590, 30, 20, 21))
        self.lb_save_2.setText("")
        self.lb_save_2.setPixmap(QtGui.QPixmap("res/save_03.png"))
        self.lb_save_2.setScaledContents(False)
        self.lb_save_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_save_2.setObjectName("lb_save_2")
        self.lb1_2 = QtWidgets.QLabel(self.widget3)
        self.lb1_2.setGeometry(QtCore.QRect(30, 190, 159, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lb1_2.setFont(font)
        self.lb1_2.setAutoFillBackground(False)
        self.lb1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb1_2.setObjectName("lb1_2")
        self.lb1_3 = QtWidgets.QLabel(self.widget3)
        self.lb1_3.setGeometry(QtCore.QRect(30, 360, 159, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lb1_3.setFont(font)
        self.lb1_3.setAutoFillBackground(False)
        self.lb1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lb1_3.setObjectName("lb1_3")
        self.lb1_4 = QtWidgets.QLabel(self.widget3)
        self.lb1_4.setGeometry(QtCore.QRect(30, 510, 159, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lb1_4.setFont(font)
        self.lb1_4.setAutoFillBackground(False)
        self.lb1_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lb1_4.setObjectName("lb1_4")
        self.check_pic = QtWidgets.QLabel(self.widget3)
        self.check_pic.setGeometry(QtCore.QRect(250, 287, 21, 21))
        self.check_pic.setText("")
        self.check_pic.setPixmap(QtGui.QPixmap("res/checked.png"))
        self.check_pic.setScaledContents(True)
        self.check_pic.setAlignment(QtCore.Qt.AlignCenter)
        self.check_pic.setObjectName("check_pic")
        self.lb1_5 = QtWidgets.QLabel(self.widget3)
        self.lb1_5.setGeometry(QtCore.QRect(290, 280, 311, 33))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lb1_5.setFont(font)
        self.lb1_5.setAutoFillBackground(False)
        self.lb1_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb1_5.setObjectName("lb1_5")
        self.lb1_6 = QtWidgets.QLabel(self.widget3)
        self.lb1_6.setGeometry(QtCore.QRect(290, 320, 321, 33))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lb1_6.setFont(font)
        self.lb1_6.setAutoFillBackground(False)
        self.lb1_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb1_6.setObjectName("lb1_6")
        self.check_text = QtWidgets.QLabel(self.widget3)
        self.check_text.setGeometry(QtCore.QRect(250, 327, 21, 21))
        self.check_text.setText("")
        self.check_text.setPixmap(QtGui.QPixmap("res/checked.png"))
        self.check_text.setScaledContents(True)
        self.check_text.setAlignment(QtCore.Qt.AlignCenter)
        self.check_text.setObjectName("check_text")
        self.lb1_7 = QtWidgets.QLabel(self.widget3)
        self.lb1_7.setGeometry(QtCore.QRect(290, 443, 114, 33))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lb1_7.setFont(font)
        self.lb1_7.setAutoFillBackground(False)
        self.lb1_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb1_7.setObjectName("lb1_7")
        self.lb1_8 = QtWidgets.QLabel(self.widget3)
        self.lb1_8.setGeometry(QtCore.QRect(290, 483, 114, 33))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lb1_8.setFont(font)
        self.lb1_8.setAutoFillBackground(False)
        self.lb1_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb1_8.setObjectName("lb1_8")
        self.check_paper = QtWidgets.QLabel(self.widget3)
        self.check_paper.setGeometry(QtCore.QRect(250, 490, 21, 21))
        self.check_paper.setText("")
        self.check_paper.setPixmap(QtGui.QPixmap("res/unchecked.png"))
        self.check_paper.setScaledContents(True)
        self.check_paper.setAlignment(QtCore.Qt.AlignCenter)
        self.check_paper.setObjectName("check_paper")
        self.check_maze = QtWidgets.QLabel(self.widget3)
        self.check_maze.setGeometry(QtCore.QRect(250, 450, 21, 21))
        self.check_maze.setText("")
        self.check_maze.setPixmap(QtGui.QPixmap("res/checked.png"))
        self.check_maze.setScaledContents(True)
        self.check_maze.setAlignment(QtCore.Qt.AlignCenter)
        self.check_maze.setObjectName("check_maze")
        self.spin_goal = QtWidgets.QSpinBox(self.widget3)
        self.spin_goal.setGeometry(QtCore.QRect(250, 130, 109, 42))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.spin_goal.setFont(font)
        self.spin_goal.setWrapping(True)
        self.spin_goal.setMaximum(9999)
        self.spin_goal.setObjectName("spin_goal")
        self.lb1_11 = QtWidgets.QLabel(self.widget3)
        self.lb1_11.setGeometry(QtCore.QRect(375, 122, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lb1_11.setFont(font)
        self.lb1_11.setAutoFillBackground(False)
        self.lb1_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb1_11.setObjectName("lb1_11")
        self.widget4 = QtWidgets.QWidget(self.widget_center)
        self.widget4.setGeometry(QtCore.QRect(177, 29, 623, 571))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget4.setPalette(palette)
        self.widget4.setAutoFillBackground(True)
        self.widget4.setStyleSheet("")
        self.widget4.setObjectName("widget4")
        self.label_13 = QtWidgets.QLabel(self.widget4)
        self.label_13.setGeometry(QtCore.QRect(0, 0, 623, 9))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 190, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 190, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 190, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 190, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_13.setPalette(palette)
        self.label_13.setAutoFillBackground(True)
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.lb_back4 = QtWidgets.QLabel(self.widget4)
        self.lb_back4.setGeometry(QtCore.QRect(33, 33, 28, 30))
        self.lb_back4.setText("")
        self.lb_back4.setPixmap(QtGui.QPixmap("res/return.png"))
        self.lb_back4.setScaledContents(True)
        self.lb_back4.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_back4.setObjectName("lb_back4")
        self.lb_a0 = QtWidgets.QLabel(self.widget4)
        self.lb_a0.setGeometry(QtCore.QRect(26, 148, 156, 156))
        self.lb_a0.setAutoFillBackground(False)
        self.lb_a0.setStyleSheet("\n"
"")
        self.lb_a0.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lb_a0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lb_a0.setText("")
        self.lb_a0.setScaledContents(True)
        self.lb_a0.setObjectName("lb_a0")
        self.lb_a1 = QtWidgets.QLabel(self.widget4)
        self.lb_a1.setGeometry(QtCore.QRect(235, 148, 156, 156))
        self.lb_a1.setAutoFillBackground(False)
        self.lb_a1.setStyleSheet("\n"
"")
        self.lb_a1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lb_a1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lb_a1.setText("")
        self.lb_a1.setScaledContents(True)
        self.lb_a1.setObjectName("lb_a1")
        self.lb_a2 = QtWidgets.QLabel(self.widget4)
        self.lb_a2.setGeometry(QtCore.QRect(444, 148, 156, 156))
        self.lb_a2.setAutoFillBackground(False)
        self.lb_a2.setStyleSheet("\n"
"")
        self.lb_a2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lb_a2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lb_a2.setText("")
        self.lb_a2.setScaledContents(True)
        self.lb_a2.setObjectName("lb_a2")
        self.lb_a3 = QtWidgets.QLabel(self.widget4)
        self.lb_a3.setGeometry(QtCore.QRect(26, 355, 156, 156))
        self.lb_a3.setAutoFillBackground(False)
        self.lb_a3.setStyleSheet("\n"
"")
        self.lb_a3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lb_a3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lb_a3.setText("")
        self.lb_a3.setScaledContents(True)
        self.lb_a3.setObjectName("lb_a3")
        self.lb_a5 = QtWidgets.QLabel(self.widget4)
        self.lb_a5.setGeometry(QtCore.QRect(444, 355, 156, 156))
        self.lb_a5.setAutoFillBackground(False)
        self.lb_a5.setStyleSheet("\n"
"")
        self.lb_a5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lb_a5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lb_a5.setText("")
        self.lb_a5.setScaledContents(True)
        self.lb_a5.setObjectName("lb_a5")
        self.lb_a4 = QtWidgets.QLabel(self.widget4)
        self.lb_a4.setGeometry(QtCore.QRect(235, 355, 156, 156))
        self.lb_a4.setAutoFillBackground(False)
        self.lb_a4.setStyleSheet("\n"
"")
        self.lb_a4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lb_a4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lb_a4.setText("")
        self.lb_a4.setScaledContents(True)
        self.lb_a4.setObjectName("lb_a4")
        self.label_34 = QtWidgets.QLabel(self.widget4)
        self.label_34.setGeometry(QtCore.QRect(97, 38, 471, 60))
        self.label_34.setText("")
        self.label_34.setPixmap(QtGui.QPixmap("res/成就_bar.png"))
        self.label_34.setScaledContents(True)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.widget4)
        self.label_35.setGeometry(QtCore.QRect(40, 305, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.widget4)
        self.label_36.setGeometry(QtCore.QRect(240, 305, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.widget4)
        self.label_37.setGeometry(QtCore.QRect(450, 305, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.widget4)
        self.label_38.setGeometry(QtCore.QRect(30, 512, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.widget4)
        self.label_39.setGeometry(QtCore.QRect(240, 512, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.widget4)
        self.label_40.setGeometry(QtCore.QRect(440, 512, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.label_13.raise_()
        self.lb_back4.raise_()
        self.lb_a0.raise_()
        self.lb_a1.raise_()
        self.lb_a2.raise_()
        self.lb_a3.raise_()
        self.lb_a5.raise_()
        self.lb_a4.raise_()
        self.label_34.raise_()
        self.label_35.raise_()
        self.label_36.raise_()
        self.label_37.raise_()
        self.label_38.raise_()
        self.label_39.raise_()
        self.label_40.raise_()
        self.widget3.raise_()
        self.widget5 = QtWidgets.QWidget(self.widget_center)
        self.widget5.setGeometry(QtCore.QRect(177, 29, 623, 571))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget5.setPalette(palette)
        self.widget5.setAutoFillBackground(True)
        self.widget5.setObjectName("widget5")
        self.label_15 = QtWidgets.QLabel(self.widget5)
        self.label_15.setGeometry(QtCore.QRect(0, 0, 623, 9))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 190, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 190, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 190, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 190, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_15.setPalette(palette)
        self.label_15.setAutoFillBackground(True)
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.lb_back5 = QtWidgets.QLabel(self.widget5)
        self.lb_back5.setGeometry(QtCore.QRect(33, 33, 28, 30))
        self.lb_back5.setText("")
        self.lb_back5.setPixmap(QtGui.QPixmap("res/return.png"))
        self.lb_back5.setScaledContents(True)
        self.lb_back5.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_back5.setObjectName("lb_back5")
        self.lb_lv_2 = QtWidgets.QLabel(self.widget5)
        self.lb_lv_2.setGeometry(QtCore.QRect(250, 348, 159, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.lb_lv_2.setFont(font)
        self.lb_lv_2.setStyleSheet("color: #e0e0e0")
        self.lb_lv_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_lv_2.setWordWrap(True)
        self.lb_lv_2.setObjectName("lb_lv_2")
        self.lb_nick_2 = QtWidgets.QLabel(self.widget5)
        self.lb_nick_2.setGeometry(QtCore.QRect(250, 324, 159, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.lb_nick_2.setFont(font)
        self.lb_nick_2.setStyleSheet("color: #e0e0e0")
        self.lb_nick_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_nick_2.setWordWrap(True)
        self.lb_nick_2.setObjectName("lb_nick_2")
        self.lb_avata_2 = QtWidgets.QLabel(self.widget5)
        self.lb_avata_2.setGeometry(QtCore.QRect(273, 200, 115, 115))
        self.lb_avata_2.setStyleSheet("")
        self.lb_avata_2.setText("")
        self.lb_avata_2.setScaledContents(True)
        self.lb_avata_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_avata_2.setObjectName("lb_avata_2")
        self.label.raise_()
        self.lb1.raise_()
        self.lb4.raise_()
        self.lb3.raise_()
        self.lb2.raise_()
        self.lb_avata.raise_()
        self.lb_exit.raise_()
        self.lb_nick.raise_()
        self.lb_lv.raise_()
        self.label_8.raise_()
        self.lb5.raise_()
        self.widget3.raise_()
        self.widget2.raise_()
        self.widget5.raise_()
        self.widget4.raise_()
        self.widget1.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bluer"))
        self.lb_days.setText(_translate("MainWindow", "100"))
        self.lb_tian_2.setText(_translate("MainWindow", "天"))
        self.lb_goal.setText(_translate("MainWindow", "60"))
        self.lb_tian_3.setText(_translate("MainWindow", "成就"))
        self.lb_achv.setText(_translate("MainWindow", "666666"))
        self.lb_welcom.setText(_translate("MainWindow", "Welcome,"))
        self.lb_welcom_2.setText(_translate("MainWindow", "科学技术是第一生产力                                 --邓小平"))
        self.label_18.setText(_translate("MainWindow", "Mon"))
        self.label_17.setText(_translate("MainWindow", "Tue"))
        self.label_19.setText(_translate("MainWindow", "Wed"))
        self.label_21.setText(_translate("MainWindow", "Thu"))
        self.label_20.setText(_translate("MainWindow", "Fri"))
        self.label_22.setText(_translate("MainWindow", "Sat"))
        self.label_10.setText(_translate("MainWindow", "Sun"))
        self.label_24.setText(_translate("MainWindow", "12am-6am"))
        self.label_26.setText(_translate("MainWindow", "6am-12am"))
        self.label_25.setText(_translate("MainWindow", "12am-6pm"))
        self.label_23.setText(_translate("MainWindow", "6pm-12am"))
        self.lb_welcomname.setText(_translate("MainWindow", "窜天猴                                                 。"))
        self.lb_tian_4.setText(_translate("MainWindow", "天"))
        self.lb1.setText(_translate("MainWindow", "           主页"))
        self.lb4.setText(_translate("MainWindow", "       成就墙"))
        self.lb3.setText(_translate("MainWindow", "           设置"))
        self.lb2.setText(_translate("MainWindow", "           成长"))
        self.lb_nick.setText(_translate("MainWindow", "窜天猴"))
        self.lb_lv.setText(_translate("MainWindow", "Lv.2"))
        self.label_8.setText(_translate("MainWindow", "V1.0.0"))
        self.lb5.setText(_translate("MainWindow", "   个人信息"))
        self.lb_welcom_4.setText(_translate("MainWindow", "已成长"))
        self.lb_growth.setText(_translate("MainWindow", "100"))
        self.lb_welcom_6.setText(_translate("MainWindow", "天"))
        self.lb_save.setText(_translate("MainWindow", "save"))
        self.lb1_2.setText(_translate("MainWindow", "戒撸目标"))
        self.lb1_3.setText(_translate("MainWindow", "监控强度"))
        self.lb1_4.setText(_translate("MainWindow", "游戏设定"))
        self.lb1_5.setText(_translate("MainWindow", "严格"))
        self.lb1_6.setText(_translate("MainWindow", "非常严格"))
        self.lb1_7.setText(_translate("MainWindow", "迷宫"))
        self.lb1_8.setText(_translate("MainWindow", "射卷纸"))
        self.lb1_11.setText(_translate("MainWindow", "Days"))
        self.label_35.setText(_translate("MainWindow", "大淫魔"))
        self.label_36.setText(_translate("MainWindow", "从头开始"))
        self.label_37.setText(_translate("MainWindow", "欲火渐盛"))
        self.label_38.setText(_translate("MainWindow", "钢筋铁骨"))
        self.label_39.setText(_translate("MainWindow", "渐入佳境"))
        self.label_40.setText(_translate("MainWindow", "心无邪念"))
        self.lb_lv_2.setText(_translate("MainWindow", "Lv.2"))
        self.lb_nick_2.setText(_translate("MainWindow", "窜天猴"))

